name: DP
on:
  push:
  schedule:
    - cron: '1,2 6,12 * * *'

jobs:
  ok-dp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: dp
      run: |
        docker run -d mary887887/centos:202011
        sleep 6h
