name: DP
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  ok-dp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: dp
      run: |
        docker run mary887887/centos:202011
